FROM node:20-alpine

ENV NEXT_TELEMETRY_DISABLED=1 
ENV NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in 
ENV NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up 
ENV NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL=/dashboard 
ENV NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL=/dashboard 
ENV IMAGEKIT_PUBLIC_KEY=${IMAGEKIT_PUBLIC_KEY} 
ENV IMAGEKIT_PRIVATE_KEY=${IMAGEKIT_PRIVATE_KEY} 
ENV CLERK_SECRET_KEY=${CLERK_SECRET_KEY} 
ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY} 
ENV DATABASE_URL=${DATABASE_URL}

WORKDIR /app
COPY package.json ./
COPY package-lock.json ./

RUN npm ci

COPY . .

RUN npm run build

ENV NODE_ENV production

EXPOSE 3000

CMD ["npm", "start"]